FROM node:18 as node

ARG PUBLIC_PATH=.
ENV PUBLIC_URL=$PUBLIC_PATH
ARG REACT_APP_CONTEXT
ENV REACT_APP_CONTEXT=$REACT_APP_CONTEXT
ARG REACT_APP_ID
ENV REACT_APP_ID=$REACT_APP_ID
ARG REACT_APP_URL
ENV REACT_APP_URL=$REACT_APP_URL
ARG REACT_APP_COMPONENTS
ENV REACT_APP_COMPONENTS=$REACT_APP_COMPONENTS
ARG REACT_APP_DEBUG
ENV REACT_APP_DEBUG=$REACT_APP_DEBUG
ARG REACT_APP_AUTHENTICATION
ENV REACT_APP_AUTHENTICATION=$REACT_APP_AUTHENTICATION
ARG REACT_APP_STANDALONE
ENV REACT_APP_STANDALONE=$REACT_APP_STANDALONE

WORKDIR /ontographer
COPY package.json .
COPY package-lock.json .
RUN npm install --production
COPY . .
RUN npx eslint --ext .ts,.tsx ./src/
RUN npm run build

FROM nginx:latest
COPY --from=node /ontographer/build /usr/share/nginx/html
